DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS items CASCADE;
DROP TABLE IF EXISTS bookings CASCADE;

CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                                        NOT NULL,
    email VARCHAR(512)                                        NOT NULL,
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items
(
    id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id     BIGINT,
    name        VARCHAR(200)                                        NOT NULL,
    description VARCHAR(200)                                        NOT NULL,
    available   BOOLEAN                                             NOT NULL,
    CONSTRAINT fk_items_to_users FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE If NOT EXISTS bookings
(
    id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT,
    item_id    BIGINT,
    start_date TIMESTAMP WITHOUT TIME ZONE                         NOT NULL,
    end_date   TIMESTAMP WITHOUT TIME ZONE                         NOT NULL,
    status     VARCHAR(100),
    CONSTRAINT fk_bookings_to_users FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_bookings_to_items FOREIGN KEY (item_id) REFERENCES items (id) ON DELETE CASCADE
);